/*
 * Code generated from Atmel Start.
 *
 * This file will be overwritten when reconfiguring your Atmel Start project.
 * Please copy examples or other code you want to keep to a separate file
 * to avoid losing it when reconfiguring.
 */
#ifndef ATMEL_START_PINS_H_INCLUDED
#define ATMEL_START_PINS_H_INCLUDED

#include <hal_gpio.h>

// SAMD51 has 14 pin functions

#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

#define GPIO_MUX8_A GPIO(GPIO_PORTA, 0)
#define GPIO_MUX8_B GPIO(GPIO_PORTA, 1)
#define GPIO_MUX8_C GPIO(GPIO_PORTA, 2)
#define GPIO_MUX8_EN GPIO(GPIO_PORTA, 3)
#define GPIO_MUX4_A GPIO(GPIO_PORTA, 4)
#define GPIO_MUX4_B GPIO(GPIO_PORTA, 5)
#define GPIO_MUX4_EN GPIO(GPIO_PORTA, 6)
#define GPIO_AD_A GPIO(GPIO_PORTA, 8)
#define GPIO_AD_B GPIO(GPIO_PORTA, 9)
#define GPIO_AD_C GPIO(GPIO_PORTA, 10)
#define PA12 GPIO(GPIO_PORTA, 12)
#define PA13 GPIO(GPIO_PORTA, 13)
#define GPIO_BUZ GPIO(GPIO_PORTA, 15)
#define GPIO_LAT_RES_P_EN GPIO(GPIO_PORTA, 16)
#define GPIO_MUX_RES_P_ENA_AL GPIO(GPIO_PORTA, 17)
#define GPIO_LAT_RES_N_EN GPIO(GPIO_PORTA, 18)
#define GPIO_MUX_RES_N_ENA_AL GPIO(GPIO_PORTA, 19)
#define PA22 GPIO(GPIO_PORTA, 22)
#define PA23 GPIO(GPIO_PORTA, 23)
#define GPIO_LAT_D0 GPIO(GPIO_PORTB, 0)
#define GPIO_LAT_D1 GPIO(GPIO_PORTB, 1)
#define GPIO_LAT_D2 GPIO(GPIO_PORTB, 2)
#define GPIO_LAT_D3 GPIO(GPIO_PORTB, 3)
#define GPIO_LAT_D4 GPIO(GPIO_PORTB, 4)
#define GPIO_LAT_D5 GPIO(GPIO_PORTB, 5)
#define GPIO_MUX2_4_A GPIO(GPIO_PORTB, 6)
#define GPIO_MUX2_4_B GPIO(GPIO_PORTB, 7)
#define GPIO_MUX2_4_EN GPIO(GPIO_PORTB, 8)
#define GPIO_SOL1 GPIO(GPIO_PORTB, 10)
#define GPIO_SOL2 GPIO(GPIO_PORTB, 11)
#define GPIO_SOL3 GPIO(GPIO_PORTB, 12)
#define GPIO_SOL4 GPIO(GPIO_PORTB, 13)
#define GPIO_SOL5 GPIO(GPIO_PORTB, 14)
#define GPIO_SOL6 GPIO(GPIO_PORTB, 15)
#define GPIO_SOL7 GPIO(GPIO_PORTB, 16)
#define GPIO_SOL8 GPIO(GPIO_PORTB, 17)
#define PB19 GPIO(GPIO_PORTB, 19)
#define PB20 GPIO(GPIO_PORTB, 20)
#define PB21 GPIO(GPIO_PORTB, 21)
#define GPIO_LED GPIO(GPIO_PORTB, 31)
#define GPIO_IN_SW1 GPIO(GPIO_PORTC, 0)
#define GPIO_IN_SW2 GPIO(GPIO_PORTC, 1)
#define GPIO_IN_SW3 GPIO(GPIO_PORTC, 2)
#define GPIO_IN_SW4 GPIO(GPIO_PORTC, 3)
#define GPIO_IN_SW6 GPIO(GPIO_PORTC, 5)
#define GPIO_IN_SW7 GPIO(GPIO_PORTC, 6)
#define GPIO_IN_SW8 GPIO(GPIO_PORTC, 7)
#define GPIO_AD_CS GPIO(GPIO_PORTC, 10)
#define GPIO_AD_RVS GPIO(GPIO_PORTC, 11)
#define GPIO_AD_RST GPIO(GPIO_PORTC, 12)
#define GPIO_LAT_VOUT_EN GPIO(GPIO_PORTC, 16)
#define GPIO_MUX_VOUT_ENA_AL GPIO(GPIO_PORTC, 17)
#define GPIO_LAT_ETC_X_EN GPIO(GPIO_PORTC, 18)
#define GPIO_MUX_ETC_X_ENA_AL GPIO(GPIO_PORTC, 19)
#define GPIO_LAT_ETC_Y_EN GPIO(GPIO_PORTC, 20)
#define GPIO_MUX_ETC_Y_ENA_AL GPIO(GPIO_PORTC, 21)
#define GPIO_LED_READY GPIO(GPIO_PORTC, 26)
#define GPIO_LED_OK GPIO(GPIO_PORTC, 27)
#define GPIO_LED_NG GPIO(GPIO_PORTC, 28)

#endif // ATMEL_START_PINS_H_INCLUDED
